### ISSUE TITLE
None of the download links work (anymore)

### ISSUE THREAD

**Issue by sixtyfive** [OpaitSoftware/TesseractStudio.Net#11]

**Comment by Bosterm** [comment]
I am having the same issue. Could you please update your download links or put the program back on your server?

**Comment by sixtyfive** [comment]
I think this was always only a kind of honeypot repository to get people to notice and then buy something. In addition, it seems to be abandoned.

**Comment by Shreeshrii** [comment]
Download link: https://opait.com/download/TessStudio/1.6.0/TessStudio.msi
Website: https://www.opait.com/TessStudio/index.html

>TessStudio is designed for ad-hoc OCR and can process one file at a time. There are two licenses available for TessStudio:

> >A Community version that is free and has a simplified user interface.
> A Registered version that is licensed per user with more advanced control of the OCR process.

>When first installed, TessStudio will be automatically licensed as a Free Community edition.

**Comment by sixtyfive** [comment]
Thanks, Shreeshrii!
