### ISSUE TITLE
Page Range Scan Only Scans First Page

### ISSUE THREAD

**Issue by nickspurry** [OpaitSoftware/TesseractStudio.Net#2]
When performing an OCR scan with page range selected to "Page" and range entered in the format [start_range]-[end_range], Tesseract Studio only performs an OCR scan on the [start_range] page. The OCR scan does not include any other pages. OCR scanning behavior appears to be equivalent to having the page range selected to "Current". Error is repeatable on multiple documents, possibly every document (occurs on every document I have tried).

Tesseract Studio Version: 1.1.5.36939
OS: Windows 10 Professional Version 1809
OCR Language: Eng
Spell Checker Dictionary: None/en_US (same behavior with both settings)
Parallel Processes: Automatic
Overwrite Existing OCR: Selected/Deselected (same behavior with both settings)

**Comment by FarhadKhalafi** [comment]
Confirmed as a defect and has been fixed as part of version 1.2 to be released shortly. Thanks for reporting.

**Comment by OpaitSoftware** [comment]
Fixed in 1.2
