### ISSUE TITLE
Source code?

### ISSUE THREAD

**Issue by fdncred** [OpaitSoftware/TesseractStudio.Net#4]
Do you plan on releasing the source code?

**Comment by OpaitSoftware** [comment]
Unfortunately cannot release the source as there are overlaps with our commercial products. Maybe at a future date. Thanks.

**Comment by stweil** [comment]
Is it possible to release those parts which don't overlap? That would make it easier to contribute bug fixes or suggestions.

Without any source this GitHub project is worthless and could as well be removed.

**Comment by tumagonx** [comment]
Is this compatible with .NET 4.0, I check the manifest and it say 4.0.30319 but crash (seems need 4.5). If source code available I'd like to compile it for .NET 4.0 or is there previous version that compatible ? I tried 1.0.0 but also crash.
