### ISSUE TITLE
Unable To Save PDF Document

### ISSUE THREAD

**Issue by nickspurry** [OpaitSoftware/TesseractStudio.Net#5]
After opening a PDF, I am unable to save that document either overwriting the existing or with a new file name.  Tesseract Studio returns an error saying "FormatException: The input string format is incorrect" (translated). Note: OS Language is French, error message in original language is "FormatException: Le format de la chaîne d'entrée est incorrect." 

It does not matter whether any OCR action has been performed on the opened document. 

Tesseract Studio Version: 1.2.0.41757
OS: Windows 10 Professional Version 1809
OS Language: French

**Comment by OpaitSoftware** [comment]
Fixed in 1.3.0

**Comment by nickspurry** [comment]
This problem still exists in 1.5.0.33332
